// Code generated by mockery v2.x.x. DO NOT EDIT.

package vehicle

import mock "github.com/stretchr/testify/mock"

// MockGeofencePublisher is an autogenerated mock type for the GeofencePublisher interface
type MockGeofencePublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: event
func (_m *MockGeofencePublisher) Publish(event *GeofenceEvent) error {
	ret := _m.Called(event)

	var r0 error
	if rf, ok := ret.Get(0).(func(*GeofenceEvent) error); ok {
		r0 = rf(event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockGeofencePublisher creates a new instance of MockGeofencePublisher. It also registers
// a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockGeofencePublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeofencePublisher {
	m := &MockGeofencePublisher{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
