// Code generated by mockery v2.x.x. DO NOT EDIT.

package vehicle

import mock "github.com/stretchr/testify/mock"

// MockRepository is an autogenerated mock type for the Repository interface
type MockRepository struct {
	mock.Mock
}

// Save provides a mock function with given fields: loc
func (_m *MockRepository) Save(loc *Location) error {
	ret := _m.Called(loc)

	var r0 error
	if rf, ok := ret.Get(0).(func(*Location) error); ok {
		r0 = rf(loc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindLatest provides a mock function with given fields: vehicleID
func (_m *MockRepository) FindLatest(vehicleID string) (*Location, error) {
	ret := _m.Called(vehicleID)

	var r0 *Location
	var r1 error

	if rf, ok := ret.Get(0).(func(string) *Location); ok {
		r0 = rf(vehicleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Location)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(vehicleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByTimeRange provides a mock function with given fields: vehicleID, start, end
func (_m *MockRepository) FindByTimeRange(vehicleID string, start int64, end int64) ([]*Location, error) {
	ret := _m.Called(vehicleID, start, end)

	var r0 []*Location
	var r1 error

	if rf, ok := ret.Get(0).(func(string, int64, int64) []*Location); ok {
		r0 = rf(vehicleID, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Location)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int64, int64) error); ok {
		r1 = rf(vehicleID, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockRepository creates a new instance of MockRepository. It also registers
// a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	m := &MockRepository{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
